version: 2.1
orbs:
  ruby: circleci/ruby@1.2.0
jobs:
  deploy:
    macos:
      xcode: “13.1.0”
    shell: /bin/bash --login -o pipefail
    steps:
      - checkout
      - ruby/install-deps
      - run:
          name: fastlane
          command: bundle exec fastlane start_new_release
workflows:
  version: 2
  release:
    jobs:
      - deploy