####
# Default job.
# This job simply defines the iOS image, some environment variables
# and stuff that all jobs should have
##
default: &defaultJob
  # Set the xcode version this virtual machine will  use
  macos:
    xcode: "13.1.0"
  # We need to set this for RVM.
  shell: /bin/bash --login
# Default workflow will run on all branches except releases
deploy-workflow: &deployWorkflow
  filters:
    branches:
      only:
        - develop
        - /release\/.*$/

version: 2.1

orbs:
  ruby: circleci/ruby@1.2.0
# Define the jobs we will be using
jobs:
  pr_check:
    macos:
      xcode: "13.1.0"
    working_directory: /Users/distiller/project
    environment:
      FL_OUTPUT_DIR: output
      FASTLANE_LANE: test
    shell: /bin/bash --login -o pipefail
    steps:
      - checkout
      - ruby/install-deps
      - run:
          name: fastlane
          command: bundle exec fastlane pr_check
      - store_artifacts:
          path: output
      - store_test_results:
          path: output/scan
  build-and-test:
      macos:
          xcode: "13.1.0"
      environment:
          FL_OUTPUT_DIR: FL_OUTPUT_DIR
      steps:
        - checkout
        - run:
            name: Install bundle
            command: bundle install
        - run:
            # working_directory:
            name: Build and run tests
            command: |
              cd ExampleSwift
              bundle install
              bundle exec pod update && pod install
              bundle update fastlane
              bundle exec fastlane scan
            environment:
                SCAN_DEVICE: iPhone 8
                SCAN_SCHEME: ExampleSwift
        - store_test_results:
            path: output/scan
        - store_artifacts:
            path: output
  deploy:
    <<: *defaultJob
    steps:
      - checkout
      - add_ssh_keys
      - restore_cache:
          key: gem-cache-{{ checksum "Gemfile.lock" }}-v2
      - run:
          name: Set Ruby Version
          command: echo "ruby-2.6.5" > ~/.ruby-version
      - run: bundle check || bundle install --path vendor/bundle
      - run:
          name: Run Deploy
          no_output_timeout: 30m
          command: ./scripts/run_deploy.sh
      - save_cache:
          key: gem-cache-{{ checksum "Gemfile.lock" }}-v2
          paths:
              - vendor/bundle
# Define the full workflow.
workflows:
  version: 2
  unit-test:
    jobs:
      - build-and-test
      - deploy:
          requires:
            - build-and-test
          <<: *deployWorkflow
